admin:
  name: "admin"
  email: "noreply@studsec.nl"
  password:
    from_env: ADMIN_PASSWORD

appearance:
  name: "StudSec CTF"
  description: "StudSec CTF"

theme:
  logo:
    from_file: images/logo.png
  small_icon:
    from_file: images/logo-icon.png
  name: core-beta
  header:
    from_file: html/theme-header.html
  footer:
    from_file: html/theme-footer.html

settings:
  challenge_visibility: public
  account_visibility: public
  score_visibility: public
  registration_visibility: public

accounts:
  team_creation: false
  team_disbanding: "disabled"
  name_changes: true
  num_teams: 0
  incorrect_submissions_per_minute: 20

challenges:
  view_self_submissions: false
  max_attempts_behavior: "timeout"
  max_attempts_timeout: 60
  hints_free_public_access: false
  challenge_ratings: "disabled"

time:
  view_after: true

legal:
  tos:
    content:
      from_file: md/tos.md

# If set to 'teams', make sure to decide on the team_creation setting below.
mode: users

pages:
  additional:
    - title: Getting Started
      route: getting-started
      format: markdown
      content:
        from_file: md/getting-started.md
    - title: "Home"
      route: "index"
      # content:
      # from_file: html/index.html
      content: |
        <script>window.location.href = "/challenges";</script>
