x-deployment: &deployment
  replicas: 1
  endpoint_mode: vip
  resources:
    limits:
      memory: 2048M
    reservations:
      memory: 128M
  placement:
    constraints:
      - node.labels.ctf == true

services:
  ctfd:
    image: ctfd/ctfd:3.8.2
    user: root
    restart: always
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://ctfd:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=7
      - SECRET_KEY=$SECRET_KEY
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
      - PRESET_ADMIN_USER=admin
      - PRESET_ADMIN_EMAIL=noreply@studsec.nl
      - PRESET_ADMIN_PASSWORD=$ADMIN_PASS
      - PRESET_ADMIN_TOKEN=$ADMIN_TOKEN
      - PLUGIN_SETTINGS_CM_API_URL=http://chall-manager:8080
      - PLUGIN_SETTINGS_CM_MANA_TOTAL=10
    volumes:
      - /srv/ctfd/CTFd/data/logs:/var/log/CTFd
      - /srv/ctfd/CTFd/data/uploads:/var/uploads
      - /srv/ctfd/CTFd/plugins:/opt/CTFd/CTFd/plugins
    depends_on:
      - db
      - cache
      - chall-manager
    healthcheck:
      test: python3 -c 'import requests; requests.get("http://localhost:8000")'
      interval: 10s
      retries: 3
      timeout: 10s
    networks:
      internal:
      traefik-public:
    deploy:
      <<: *deployment
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.lbswarm=true"
        - "traefik.swarm.network=traefik-public"
        # https entrypoint
        - "traefik.http.routers.ctfd-https.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.ctfd-https.entrypoints=https"
        - "traefik.http.routers.ctfd-https.tls=true"
        # explicitly use le as certresolver
        - "traefik.http.routers.ctfd-https.tls.certresolver=letsencrypt"
        # Needed for ctfd behind reverse proxy
        - "traefik.http.routers.ctfd-https.middlewares=forward-proto@file"
        - "traefik.http.routers.ctfd-https.service=ctfdHttpsService"
        - "traefik.http.services.ctfdHttpsService.loadbalancer.server.port=8000"
  db:
    image: mariadb:10.11
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=ctfd
      - MARIADB_USER=ctfd
      - MARIADB_PASSWORD=ctfd
      - MARIADB_DATABASE=ctfd
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - /srv/ctfd/CTFd/.data/mysql:/var/lib/mysql
    networks:
      internal:
    # This command is required to set important mariadb defaults
    command:
      [
        mysqld,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci,
        --wait_timeout=28800,
        --log-warnings=0,
      ]
    deploy:
      <<: *deployment

  cache:
    image: redis:4
    restart: always
    volumes:
      - /srv/ctfd/CTFd/.data/redis:/data
    networks:
      internal:
    deploy:
      <<: *deployment

  chall-manager:
    image: ctferio/chall-manager:v0.5.3
    networks:
      internal:
    environment:
      OCI_USERNAME: admin
      OCI_PASSWORD: $ADMIN_PASS
    volumes:
      - /root/.docker/config.json:/root/.docker/config.json:ro
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      <<: *deployment

  chall-manager-janitor:
    image: ctferio/chall-manager-janitor:v0.5.3
    networks:
      internal:
    environment:
      URL: chall-manager:8080
      TICKER: 1m
    deploy:
      <<: *deployment

  ctfd-setup:
    image: ctferio/ctfd-setup:v1.7.1
    environment:
      URL: http://ctfd:8000
      FILE: /opt/ctfd-setup/.ctfd.yaml
      DIRECTORY: /opt/ctfd-setup
    env_file:
      - /srv/ctfd/ctfd-setup/.env
    volumes:
      - /srv/ctfd/ctfd-setup:/opt/ctfd-setup
    networks:
      internal:
    depends_on:
      - ctfd
    deploy:
      <<: *deployment
      restart_policy:
        condition: on-failure

networks:
  traefik-public:
    external: true
  internal:
    driver: overlay
