- name: Ensure traefik directory exists
  ansible.builtin.file:
    path: "/srv/traefik"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Copy Traefik configuration files
  ansible.posix.synchronize:
    src: "./traefik/"
    dest: "/srv/traefik/"
    recursive: true
  become: false

- name: Substitute environment variables in docker-compose.yml
  ansible.builtin.shell: |
    envsubst < /srv/traefik/traefik.yml > /srv/traefik/traefik.yml.tmp
    mv /srv/traefik/traefik.yml.tmp /srv/traefik/traefik.yml
    envsubst < /srv/traefik/docker-compose.yml > /srv/traefik/docker-compose.yml.tmp
    mv /srv/traefik/docker-compose.yml.tmp /srv/traefik/docker-compose.yml
  environment:
    EMAIL: "{{ CERT_EMAIL }}"
  changed_when: true

- name: Create traefik swarm network
  community.docker.docker_network:
    name: traefik-public
    driver: overlay
    scope: swarm
    state: present

- name: Build and start Traefik
  community.docker.docker_stack:
    compose: /srv/traefik/docker-compose.yml
    state: present
    name: traefik-public
