- name: Manager - Initialization
  hosts: manager
  become: true
  vars_files:
    - .env.yml
  tags:
    - setup
  vars:
    # installed by geerlingguy.pip
    pip_install_packages:
      - name: docker
      - name: jsondiff
  environment:
    NEEDRESTART_MODE: automatically

  pre_tasks:
    - name: Wait for cloud-init / user-data to finish
      # https://serverfault.com/a/1021022
      ansible.builtin.command: cloud-init status --wait
      changed_when: false
      # no cloud-init, no problem
      failed_when: false
    - name: Populate Apt's Cache with package definitions to avoid "no such package" errors
      # https://github.com/geerlingguy/ansible-role-pip/issues/49#issuecomment-1824708282
      ansible.builtin.apt:
        update_cache: true
    - name: Install rsync
      ansible.builtin.apt:
        name: rsync
        state: present
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - geerlingguy.git

# SETUP SWARM
- name: Setup Swarm - swarm manager initialization
  hosts: manager
  become: true
  tags:
    - swarm
  tasks:
    - name: Initialize Docker Swarm on Manager
      community.docker.docker_swarm:
        state: present
        advertise_addr: "{{ ansible_default_ipv4.address }}"
      register: swarm_init

    - name: Retrieve Swarm Info (to get Join Tokens)
      community.docker.docker_swarm_info:
      register: swarm_info

    - name: Set Join Token Fact
      ansible.builtin.set_fact:
        worker_join_token: "{{ swarm_info.swarm_facts.JoinTokens.Worker }}"
        manager_ip: "{{ ansible_default_ipv4.address }}"

    - name: Set manager label
      community.docker.docker_node:
        hostname: "{{ ansible_hostname }}"
        labels:
          manager: "true"

    - name: Create net swarm network
      community.docker.docker_network:
        name: net
        driver: overlay
        scope: swarm
        state: present

- name: Setup Swarm - swarm workers initialization
  hosts: all
  become: true
  tags:
    - swarm
  tasks:
    - name: Join Swarm as Worker
      when: "'manager' not in group_names"
      community.docker.docker_swarm:
        state: join
        join_token: "{{ hostvars[groups['manager'][0]]['worker_join_token'] }}"
        remote_addrs:
          ["{{ hostvars[groups['manager'][0]]['manager_ip'] }}:2377"]

- name: Manager - Deploy Traefik
  hosts: manager
  become: true
  vars_files:
    - .env.yml
  tags:
    - traefik
  tasks:
    - name: Setup Traefik for the manager node
      ansible.builtin.import_tasks: traefik/ansible.yml

- name: Manager - Deploy Registry
  hosts: manager
  become: true
  vars_files:
    - .env.yml
  tags:
    - registry
  tasks:
    - name: Setup Registry for the manager node
      ansible.builtin.import_tasks: registry/ansible.yml

- name: Manager - Deploy Monitoring
  hosts: manager
  become: true
  vars_files:
    - .env.yml
  tags:
    - monitoring
  tasks:
    - name: Setup Monitoring for the manager node
      ansible.builtin.import_tasks: monitoring/ansible.yml
