- name: CTF - Setup
  hosts: ctf
  remote_user: root
  become: true
  vars_files:
    - .env.yml
  tags:
    - setup
  vars:
    # installed by geerlingguy.pip
    pip_install_packages:
      - name: docker
      - name: jsondiff
      - name: cryptography
  environment:
    NEEDRESTART_MODE: automatically

  pre_tasks:
    - name: Wait for cloud-init / user-data to finish
      # https://serverfault.com/a/1021022
      ansible.builtin.command: cloud-init status --wait
      changed_when: false
    - name: Populate Apt's Cache with package definitions to avoid "no such package" errors
      # https://github.com/geerlingguy/ansible-role-pip/issues/49#issuecomment-1824708282
      ansible.builtin.apt:
        update_cache: true
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - geerlingguy.git

  tasks:
    - name: Set ctf label
      community.docker.docker_node:
        hostname: "{{ ansible_hostname }}"
        role: manager
        labels:
          ctf: "true"
      delegate_to: "{{ groups['manager'][0] }}"

    - name: Login to remote Docker registry
      community.docker.docker_login:
        registry_url: "registry.{{ CTF_DOMAIN }}"
        username: "admin"
        password: "{{ ADMIN_PASS }}"

- name: CTF - CTFd setup
  hosts: ctf
  remote_user: root
  become: true
  vars_files:
    - .env.yml
  vars:
    ctfd_sync_paths:
      - src: "./ctfd/"
        dest: "/srv/ctfd/"
      - src: "../config/ctfd/"
        dest: "/srv/ctfd/CTFd/"
      - src: "../config/ctfd-setup/"
        dest: "/srv/ctfd/ctfd-setup/"
      - src: "../config/chall-manager/"
        dest: "/srv/ctfd/chall-manager/"
  tags:
    - ctfd
  tasks:
    - name: Copy CTFd/chall-manager files
      ansible.posix.synchronize:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        recursive: true
      loop: "{{ ctfd_sync_paths }}"
      become: false

    - name: Create keys for chall-manager
      community.crypto.openssh_keypair:
        path: "/srv/ctfd/chall-manager/id_ed25519"
        type: ed25519

    - name: Read public key for chall-manager
      ansible.builtin.slurp:
        src: "/srv/ctfd/chall-manager/id_ed25519.pub"
      register: chall_manager_pubkey

    - name: Add public key to authorized_keys for all chall nodes
      ansible.posix.authorized_key:
        key: "{{ chall_manager_pubkey.content | b64decode }}"
        user: user
        state: present
      delegate_to: "{{ item }}"
      loop: "{{ groups['challs'] }}"

    - name: Substitute environment variables in docker-compose.yml
      ansible.builtin.shell: |
        envsubst < /srv/ctfd/docker-compose.yml > /srv/ctfd/docker-compose.yml.tmp
        mv /srv/ctfd/docker-compose.yml.tmp /srv/ctfd/docker-compose.yml
      environment:
        DOMAIN: "{{ CTF_DOMAIN }}"
        SECRET_KEY: "{{ SECRET_KEY }}"
        ADMIN_PASS: "{{ ADMIN_PASS }}"
        ADMIN_TOKEN: "{{ ADMIN_TOKEN }}"
      changed_when: true

    - name: Build and start CTFd docker
      community.docker.docker_stack:
        compose: /srv/ctfd/docker-compose.yml
        state: present
        name: ctfd

- name: CTF - pulumi setup
  hosts: ctf
  remote_user: root
  become: true
  vars_files:
    - .env.yml
  tags:
    - pulumi
  tasks:
    - name: Install Go 1.24
      ansible.builtin.shell: |
        GO_VERSION="1.24.1"
        curl -fsSL -o /tmp/go${GO_VERSION}.linux-amd64.tar.gz "https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz"
        rm -rf /usr/local/go
        tar -C /usr/local -xzf /tmp/go${GO_VERSION}.linux-amd64.tar.gz
        ln -sf /usr/local/go/bin/go /usr/local/bin/go
        ln -sf /usr/local/go/bin/gofmt /usr/local/bin/gofmt
      changed_when: true

    - name: Install oras
      ansible.builtin.shell: |
        VERSION="1.3.0"
        curl -fsSLO "https://github.com/oras-project/oras/releases/download/v${VERSION}/oras_${VERSION}_linux_amd64.tar.gz"
        mkdir -p oras-install/
        tar -zxf oras_${VERSION}_linux_amd64.tar.gz -C oras-install/
        chmod +x oras-install/oras
        mv oras-install/oras /usr/local/bin/oras
        rm -rf oras_${VERSION}_linux_amd64.tar.gz oras-install/
      changed_when: true

    - name: Install pulumi scenario
      ansible.builtin.command: ./build.sh
      args:
        chdir: /srv/ctfd/chall-manager
      environment:
        PATH: "/usr/local/go/bin:/usr/local/bin:{{ ansible_env.PATH }}"
        REGISTRY: "registry.{{ CTF_DOMAIN }}/"
      changed_when: true
