{
 "title": "Partner Purchases",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Barenecessities purchases",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "movingAverage(nonNegativeDerivative(core.production.partners.barenecessities.sales.total), '1hour')"
    }
   ]
  },
  {
   "title": "CDW Purchases",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "target": "movingAverage(nonNegativeDerivative(core.production.partners.cdw.sales.total), '1hour')"
    }
   ]
  },
  {
   "title": "Footjoy Purchases",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "target": "movingAverage(nonNegativeDerivative(core.production.partners.footjoy.sales.total), '1hour')"
    }
   ]
  },
  {
   "title": "Stuartweitzman Purchase",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "target": "movingAverage(nonNegativeDerivative(core.production.partners.stuartweitzman.sales.total), '1hour')"
    }
   ]
  },
  {
   "title": "taylormadegolf Purchases",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "target": "movingAverage(nonNegativeDerivative(core.production.partners.taylormadegolf.sales.total), '1hour')"
    }
   ]
  },
  {
   "title": "titleist Purchases",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "target": "movingAverage(nonNegativeDerivative(core.production.partners.titleist.sales.total), '1hour')"
    }
   ]
  },
  {
   "title": "bushnell Purchases",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "target": "movingAverage(nonNegativeDerivative(core.production.partners.bushnell.sales.total), '1hour')"
    }
   ]
  },
  {
   "title": "gigaparts Purchases",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "target": "movingAverage(nonNegativeDerivative(core.production.partners.gigaparts.sales.total), '1hour')"
    }
   ]
  },
  {
   "title": "herroom Purchases",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "target": "movingAverage(nonNegativeDerivative(core.production.partners.herroom.sales.total), '1hour')"
    }
   ]
  },
  {
   "title": "integrativenutrition Purchases",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 30 },
   "targets": [
    {
     "target": "movingAverage(nonNegativeDerivative(core.production.partners.integrativenutrition.sales.total), '1hour')"
    }
   ]
  },
  {
   "title": "pyramydair Purchases",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 30 },
   "targets": [
    {
     "target": "movingAverage(nonNegativeDerivative(core.production.partners.pyramydair.sales.total), '1hour')"
    }
   ]
  },
  {
   "title": "turtlebeach Purchases",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 30 },
   "targets": [
    {
     "target": "movingAverage(nonNegativeDerivative(core.production.partners.turtlebeach.sales.total), '1hour')"
    }
   ]
  }
 ]
}