{
 "title": "Partner Visits",
 "time": { "from": "now/fy", "to": "now" },
 "panels": [
  {
   "title": "Barenecessities Visits",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "movingAverage(core.production.partners.barenecessities.visitors.visitors, '30min')"
    },
    {
     "target": "movingAverage(core.production.partners.barenecessities.visitors.visitors, '7d')"
    }
   ]
  },
  {
   "title": "CDW Visits",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "target": "movingAverage(core.production.partners.cdw.visitors.visitors, '30min')"
    },
    {
     "target": "movingAverage(core.production.partners.cdw.visitors.visitors, '7d')"
    }
   ]
  },
  {
   "title": "Footjoy Visits",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "target": "movingAverage(core.production.partners.footjoy.visitors.visitors, '30min')"
    },
    {
     "target": "movingAverage(core.production.partners.footjoy.visitors.visitors, '7d')"
    }
   ]
  },
  {
   "title": "Stuartweitzman Visits",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "target": "movingAverage(core.production.partners.stuartweitzman.visitors.visitors, '30min')"
    },
    {
     "target": "movingAverage(core.production.partners.stuartweitzman.visitors.visitors, '7d')"
    }
   ]
  },
  {
   "title": "taylormadegolf Visits",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "target": "movingAverage(core.production.partners.taylormadegolf.visitors.visitors, '30min')"
    },
    {
     "target": "movingAverage(core.production.partners.taylormadegolf.visitors.visitors, '7d')"
    }
   ]
  },
  {
   "title": "titleist Visits",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "target": "movingAverage(core.production.partners.titleist.visitors.visitors, '30min')"
    },
    {
     "target": "movingAverage(core.production.partners.titleist.visitors.visitors, '7d')"
    }
   ]
  },
  {
   "title": "bushnell Visits",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "target": "movingAverage(core.production.partners.bushnell.visitors.visitors, '30min')"
    },
    {
     "target": "movingAverage(core.production.partners.bushnell.visitors.visitors, '7d')"
    }
   ]
  },
  {
   "title": "gigaparts Visits",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "target": "movingAverage(core.production.partners.gigaparts.visitors.visitors, '30min')"
    },
    {
     "target": "movingAverage(core.production.partners.gigaparts.visitors.visitors, '7d')"
    }
   ]
  },
  {
   "title": "herroom Visits",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "target": "movingAverage(core.production.partners.herroom.visitors.visitors, '30min')"
    },
    {
     "target": "movingAverage(core.production.partners.herroom.visitors.visitors, '7d')"
    }
   ]
  },
  {
   "title": "integrativenutrition Visits",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 30 },
   "targets": [
    {
     "target": "movingAverage(core.production.partners.integrativenutrition.visitors.visitors, '30min')"
    },
    {
     "target": "movingAverage(core.production.partners.integrativenutrition.visitors.visitors, '7d')"
    }
   ]
  },
  {
   "title": "pyramydair Visits",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 30 },
   "targets": [
    {
     "target": "movingAverage(core.production.partners.pyramydair.visitors.visitors, '30min')"
    },
    {
     "target": "movingAverage(core.production.partners.pyramydair.visitors.visitors, '7d')"
    }
   ]
  },
  {
   "title": "turtlebeach Visits",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 30 },
   "targets": [
    {
     "target": "movingAverage(core.production.partners.turtlebeach.visitors.visitors, '30min')"
    },
    {
     "target": "movingAverage(core.production.partners.turtlebeach.visitors.visitors, '7d')"
    }
   ]
  }
 ]
}