{
 "title": "Docker Swarm Services",
 "description": "Docker Swarm stacks and services metrics",
 "tags": [ "swarmprom" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "node_id", "label": "Swarm Node", "query": "node_meta" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count(container_tasks_state{container_label_com_docker_swarm_node_id =~\"$node_id\"}) by (container_label_com_docker_swarm_node_id))"
    }
   ]
  },
  {
   "title": "Stacks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count(container_tasks_state{container_label_com_docker_stack_namespace=~\".+\", container_label_com_docker_swarm_node_id=~\"$node_id\"}) by (container_label_com_docker_stack_namespace))"
    }
   ]
  },
  {
   "title": "Services",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count(container_tasks_state{container_label_com_docker_swarm_service_name=~\".+\", container_label_com_docker_swarm_node_id=~\"$node_id\"}) by (container_label_com_docker_swarm_service_name))"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{container_label_com_docker_swarm_node_id=~\"$node_id\"}[5m])) "
    }
   ]
  },
  {
   "title": "Service Tasks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_last_seen{container_label_com_docker_swarm_node_id=~\"$node_id\"}[5m])) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{ container_label_com_docker_swarm_service_name }}"
    }
   ]
  },
  {
   "title": "Health Checks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(engine_daemon_health_checks_total[$interval]) \n  * on(instance) group_left(node_id) \n  label_replace(swarm_node_info{node_id=~\"$node_id\"}, \"instance\", \"$1:9323\", \"node_address\", \"(.*)\")\n) by (node_id)",
     "legendFormat": "checks"
    },
    {
     "expr": "sum(\n  increase(engine_daemon_health_checks_failed_total[$interval]) \n  * on(instance) group_left(node_id) \n  label_replace(swarm_node_info{node_id=~\"$node_id\"}, \"instance\", \"$1:9323\", \"node_address\", \"(.*)\")\n) by (node_id)",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "CPU usage by Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  sum(container_memory_working_set_bytes{container_label_com_docker_swarm_service_name=~\".+\"}) by (container_label_com_docker_swarm_service_name)\n  / \n  on() group_left() sum(node_memory_MemTotal_bytes)\n) * 100",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\"}[$interval]) * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"}) * 100 / count(node_cpu_seconds_total{mode=\"user\"} * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"}) "
    }
   ]
  },
  {
   "title": "CPU usage by Container (top 10)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10, \n  sum(\n    irate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\".+\"}[$interval])\n  ) by (container_label_com_docker_swarm_service_name)\n) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory usage by Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\".+\"}) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "Used {{container_label_com_docker_swarm_service_name}}"
    },
    {
     "expr": "sum(container_memory_cache{container_label_com_docker_swarm_service_name=~\".+\"}) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "Cached {{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum((node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"} * 100) / count(node_meta * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"})"
    }
   ]
  },
  {
   "title": "Memory usage by Container (top 10)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(10, \n  avg_over_time(\n    sum(container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\".+\"}) \n    by (container_label_com_docker_swarm_service_name)[$interval:]\n  )\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network received by Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{container_label_com_docker_swarm_node_id=~\"$node_id\"}[$interval])) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Network transmitted by Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_node_id=~\"$node_id\"}[$interval])) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Cluster Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "Transmited"
    }
   ]
  },
  {
   "title": "Cluster IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_total[$interval]) )",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(irate(container_fs_writes_total[$interval])) ",
     "legendFormat": "Writes "
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum((node_filesystem_free_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"} * 100) / count(node_meta * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"})"
    }
   ]
  },
  {
   "title": "Docker Engine Info",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "sum(engine_daemon_engine_info * on(instance) group_left(node_id) swarm_node_info) by (kernel, os, graphdriver, version, node_id)"
    }
   ]
  }
 ]
}